### ISSUE TITLE
failed during retrain with error on factoryai 

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/azure-intelligent-edge-patterns#123]
Getting this issue
- When I am trying to retrain, 

vision_on_edge.azure_training.models.Project.DoesNotExist: Project matching query does not exist.
[09-Jul-2020 15:55:18] ERROR django.request       : Internal Server Error: /api/projects/1/export
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/app/vision_on_edge/azure_training/api/views.py", line 250, in export
    project_obj = Project.objects.get(pk=project_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
vision_on_edge.azure_training.models.Project.DoesNotExist: Project matching query does not exist.
[09/Jul/2020 15:55:18] "GET /api/projects/1/export HTTP/1.1" 500 15824

**Comment by initmahesh** [comment]
cannot repro
