### ISSUE TITLE
Retrain can only do once ,After that. images will not be captured for retrain.

### ISSUE THREAD

**Issue by tommywu052** [Azure-Samples/azure-intelligent-edge-patterns#131]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Retrain can only do once ( It will work at first time to identify manually). After that. images will not be captured for retrain. 

### Any log messages given by the failure
>
Errors at InferenceModule------
ERROR:main:Exception on /update_model [GET]
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/miniconda/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/miniconda/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/miniconda/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/miniconda/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/miniconda/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/opt/miniconda/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/opt/miniconda/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/miniconda/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/miniconda/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/miniconda/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 429, in update_model
    get_file_zip(model_uri, MODEL_DIR)
  File "/app/utility.py", line 87, in get_file_zip
    remotefile = urlopen(url)
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/miniconda/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
INFO:werkzeug:172.18.0.3 - - [13/Jul/2020 06:11:37] "GET /update_model?model_uri=https%3A%2F%2Firisscuprodstore.blob.core.windows.net%2Fm-2ab61ffd8f654cbb9fd769c94433de56%2Ff53171adc8b04247937fcb00abc5f255.ONNX.zip%3Fsv%3D2017-04-17%26sr%3Db%26sig%3DP7tiBoN5bhkyp03mf0SyAwJZ869QaO4Z5p4THpu3QEk%253D%26se%3D2020-07-14T06%253A02%253A52Z%26sp%3Dr HTTP/1.1" 500 -
INFO:werkzeug:172.18.0.3 -

![image](https://user-images.githubusercontent.com/5437788/87277028-10cb5400-c514-11ea-945c-db966ee1f188.png)

### Expected/desired behavior
>
Should be able to capture images always for retrain if images accuracy is set between min and max

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ubuntu
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by initmahesh** [comment]
should be fixed in new release please try and update
