### ISSUE TITLE
module fails to deploy if we pass empty CV key and endpoint ,,,

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/azure-intelligent-edge-patterns#144]
How to repro try to deploy a module using batch file and press enter when the prompt ask for 

You can use your existing Custom Vision service, or create a new one
Would you like to use an existing Custom Vision Service? Y
Endpoint and key information can be found at www.customvision.ai - settings(top right corner)
Please enter your Custom Vision endpoint:
Please enter your Custom Vision Key:

LOga re here 

  at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Models.EnvVar..ctor(String key, String value) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/models/EnvVar.cs:line 8
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Commands.CreateOrUpdateCommand.<>c.<GetEnvVars>b__14_0(KeyValuePair`2 m) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs:line 95
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Commands.CreateOrUpdateCommand.GetEnvVars(IDictionary`2 moduleEnvVars, IModuleIdentity identity, IConfigSource configSource) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs:line 95
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Commands.CreateOrUpdateCommand.Build(IModuleManager moduleManager, IModule module, IModuleIdentity identity, IConfigSource configSource, Object settings, Operation operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs:line 198
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommandFactory`1.UpdateAsync(Option`1 current, IModuleWithIdentity next, IRuntimeInfo runtimeInfo, Boolean start)
   at Microsoft.Azure.Devices.Edge.Agent.Core.MetricsCommandFactory.UpdateAsync(IModule current, IModuleWithIdentity next, IRuntimeInfo runtimeInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/MetricsCommandFactory.cs:line 38
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.UpdateAsync(IModule current, IModuleWithIdentity next, IRuntimeInfo runtimeInfo) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 23
   at Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner.ProcessAddedUpdatedModules(IList`1 modules, IImmutableDictionary`2 moduleIdentities, Func`2 createUpdateCommandMaker) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs:line 250
   at Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner.PlanAsync(ModuleSet desired, ModuleSet current, IRuntimeInfo runtimeInfo, IImmutableDictionary`2 moduleIdentities) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs:line 93
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 137
<4> 2020-07-22 19:23:10.030 +00:00 [WRN] - Reconcile failed because of the an exception
System.ArgumentException: value is null or whitespace.
   at Microsoft.Azure.Devices.Edge.Util.Preconditions.CheckNonWhiteSpace(String value, String paramName) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Preconditions.cs:line 191
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Models.EnvVar..ctor(String key, String value) 

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by initmahesh** [comment]
fixed in new build
