### ISSUE TITLE
on start if we do ntot choose any project and start the demo model with demo video the module fails 

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/azure-intelligent-edge-patterns#147]
How to repro 
Start a new deployment with no camera and CV keys only 
- Do not select any project on settings page 
- Go to demo and try running the demo 

Expeceted 
Demos should work 

Actual 
Demo get stuck and we get this error in web module log

TTP GET /api/projects/2/export 200 [0.03, 73.59.105.21:60681]
[22-Jul-2020 22:44:24] INFO django.channels.server : HTTP GET /api/projects/2/export 200 [0.03, 73.59.105.21:60681]
[22-Jul-2020 22:44:27] INFO vision_on_edge.azure_training.api.views : exporting project. Project Id: {6}
Internal Server Error: /api/projects/6/export
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/app/vision_on_edge/azure_training/api/views.py", line 111, in export
    project_obj = Project.objects.get(pk=project_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
vision_on_edge.azure_training.models.Project.DoesNotExist: Project matching query does not exist.

And this in the Inference sample module 

raceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/opt/miniconda/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

ERROR:azure.iot.device.common.pipeline.pipeline_ops_base:ConnectOperation: completing with error None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
WARNING:azure.iot.device.common.pipeline.pipeline_stages_base:RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852).  Setting timer.
INFO:werkzeug:172.18.0.2 - - [22/Jul/2020 22:48:10] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [22/Jul/2020 22:48:15] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [22/Jul/2020 22:48:20] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:172.18.0.2 - - [22/Jul/2020 22:48:25] "GET /metrics HTTP/1.1" 200 -
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:RetryStage(ConnectOperation): retrying
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): connecting
INFO:azure.iot.device.common.mqtt_transport:connecting to mqtt broker
INFO:azure.iot.device.common.mqtt_transport:Connect using port 8883 (TCP)
ERROR:azure.iot.device.common.pipeline.pipeline_stages_mqtt:transport.connect raised error
ERROR:azure.iot.device.common.pipeline.pipeline_stages_mqtt:Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 340, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/opt/miniconda/lib/python3.6/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/opt/miniconda/lib/python3.6/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/opt/miniconda/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/miniconda/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/opt/miniconda/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

ERROR:azure.iot.device.common.pipeline.pipeline_ops_base:ConnectOperation: completing with error None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
WARNING:azure.iot.device.common.pipeline.pipeline_stages_base:RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852).  Setting timer.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by initmahesh** [comment]
Please try to repro and see if we can fix it ...
